import { getSession, useSession } from 'next-auth/react'
import Head from 'next/head'
import Image from 'next/image'
import Brands from '../components/Brands'
import Header from '../components/Header'
import Hero from '../components/Hero'
import MovieCollection from '../components/MovieCollection'
import ShowCollection from '../components/ShowCollection'
import Slider from '../components/Slider'
import styles from '../styles/Home.module.css'

export default function Home({
  popularMovies,
  popularShows,
  top_ratedMovies,
  top_ratedShows,
}) {

   console.log(popularMovies)
  const {data:session} = useSession()

  return (
    <div className={styles.container}>
      <Head>
        <title>DisneyPlus+ </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <Header/>

       {!session ? 

       (

       <Hero/>
       ) : (
         <main className='relative min-h-screen after:bg-home after:bg-center after:bg-cover after:bg-no-repeat after:bg-fixed after:absolute after:inset-0 after:z-[-1]'>
           <Slider/>
           <Brands/>
           <MovieCollection results={popularMovies} title="Popular Movies"/>
           <ShowCollection results={popularShows} title="Popular Shows"/>

           <MovieCollection results={top_ratedMovies} title="Top Rated Movies"/>
           <ShowCollection results={top_ratedShows} title="Top Rated Shows"/>
         </main>
         )}

    </div>
  )
}

export async function getServerSideProps(context){
  const session = await getSession(context);

  const [popularMoviesRes, popularShowsRes, top_ratedMoviesRes, top_ratedShowsRes,] = await Promise.all([
    fetch(`https://api.themoviedb.org/3/movie/popular?api_key=${process.env.API_KEY}&language=en-US&page=1`),

    fetch(`https://api.themoviedb.org/3/tv/popular?api_key=${process.env.API_KEY}&language=en-US&page=1`),

    fetch(`https://api.themoviedb.org/3/movie/top_rated?api_key=${process.env.API_KEY}&language=en-US&page=1`),

    fetch(`https://api.themoviedb.org/3/tv/top_rated?api_key=${process.env.API_KEY}&language=en-US&page=1`),
  ]);

  const [popularMovies, popularShows, top_ratedMovies, top_ratedShows] =
    await Promise.all([
      popularMoviesRes.json(),
      popularShowsRes.json(),
      top_ratedMoviesRes.json(),
      top_ratedShowsRes.json(),
    ]);

  return{
      props: {
      session,
      popularMovies: popularMovies.results || null,
      popularShows: popularShows.results || null,
      top_ratedMovies: top_ratedMovies.results || null,
      top_ratedShows: top_ratedShows.results || null,
      },
  };
}